### PR TITLE
Removed strings to atoms transformations

### PR DESCRIPTION
**Pull request by JustMikey**
I tested it with the HTTP proxy and it works as expected. What do you think?

### CODE REVIEW

**Comment by AntonFagerberg** [comment]
Thanks! I'll have to try it with the SOCKS5 proxy first, otherwise it looks good!

**Comment by JustMikey** [comment]
Yeah, absolutely, hopefully it will work :)

**Comment by AntonFagerberg** [comment]
Hey, it doesn't seem to work. If I use `"localhost"` then I get the following failure:

```elixir
18:50:34.864 [error] Task #PID<0.1584.0> started from #PID<0.1566.0> terminating
** (ArgumentError) argument error
    (kernel) gen_tcp.erl:148: :gen_tcp.connect/4
    (hackney) src/hackney_socks5.erl:53: :hackney_socks5.connect/4
    (hackney) src/hackney_connect.erl:245: :hackney_connect.do_connect/5
    (hackney) src/hackney_connect.erl:36: :hackney_connect.connect/5
    (hackney) src/hackney.erl:328: :hackney.request/5
    (rackla) lib/rackla/rackla.ex:104: anonymous fn/2 in Rackla.request/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<19.128367465/0 in Rackla.request/2>
    Args: []
```

If I use the Erlang string `'localhost'` then it works.

Do you want to try replacing `String.to_atom` with `String.to_char_list` and see if it works for you with the HTTP proxy?

**Comment by JustMikey** [comment]
Yeah I will try it tomorrow and let you know :)

**Comment by JustMikey** [comment]
I am not sure but I think we may need to use `String.to_char_list` only for the host param, `proxy_auth` seems to be working with binaries (Elixir strings) alright.

**Comment by AntonFagerberg** [comment]
(Ugh, these two string representations are messy...)

I believe you're correct regarding auth.
https://github.com/benoitc/hackney/blob/294aa7cfc14326c875fe321504245df4fd632fd3/src/hackney_socks5.erl#L167-L169

https://github.com/benoitc/hackney/blob/d8c0add32cb2a9742cf646eac84c0c9a7bc1674f/src/hackney_http_connect.erl#L158-L159

The PR looks good, big thanks!

I plan to wrote some additional documentation and make a release on Thursday.

**Comment by JustMikey** [comment]
Sure, thank you very much again :)

**Pull request merged**
