### PR TITLE
Add remix dependency

### PR DESCRIPTION
**Pull request by pap**
Enable auto reloading in dev environment #4

### CODE REVIEW

**Comment by pap** [comment]
@AntonFagerberg currently remix will issue a warning on deps.compile:
> warning: the dependency :remix requires Elixir "~> 1.0.0" but you are running on v1.1.1

I have created a PR on the remix repo that fixes it. If you want to try in the meantime use this for the remix dependency entry on mix.exs:

```{:remix, github: "pap/remix", branch: "elixir-version-fix-warning", only: :dev}```

I don't know if you wanted an approach other than adding another dependency but remix code is really simple and I do prefer use "composition" than reinventing the wheel. Let me know if you want any other the of approach.

**Comment by AntonFagerberg** [comment]
@pap Thank you so much for the PR! I have only skimmed the code but it looks good to me. I'll try to evaluate it this weekend and merge it if everything looks good :)

**Comment by pap** [comment]
@AntonFagerberg It seems the PR for remix was merged. I'll check tonight if the Hex package was updated and if so will bump the version in mix.ex
This way we avoid a warning on dependency compilation.

**Comment by AntonFagerberg** [comment]
@pap Perfect, I'll be sure to hold on until it is updated.

**Comment by pap** [comment]
@AntonFagerberg the remix package is updated. No more warnings about the elixir version.

**Comment by AntonFagerberg** [comment]
Now I've finally had the time to evaluate this for a little while and I really like it. This really improves the development experience a lot so big thanks for this suggestion and the pull request!

The only thing which bothers me is that if you run `mix server` or run Rackla from escript with `env=DEV` you'll end up with this error message:

```elixir
21:57:37.238 [error] GenServer Remix.Worker terminating
** (UndefinedFunctionError) undefined function: Mix.Tasks.Compile.Elixir.run/1 (module Mix.Tasks.Compile.Elixir is not available)
    Mix.Tasks.Compile.Elixir.run(["--ignore-module-conflict"])
    (remix) lib/remix.ex:35: Remix.Worker.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: :poll_and_reload
State: %Remix.Worker.State{last_mtime: nil}
```

It would be nice to get rid of this error message but it is not a deal breaker since you should only use escript and `mix server` with prod mod. (This should probably be solved in remix and not in this project. I'll add an issue to their GitHub repo.)

**Comment by pap** [comment]
@AntonFagerberg Cool. I'll try to check it on remix ! Btw I am really enjoying Rackla ! Ty!

**Pull request merged**
